# Generated by Django 2.2.3 on 2022-11-10 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='nombre_M',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.Marca'),
        ),
    ]
