# Generated by Django 4.1.3 on 2022-11-12 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_alter_producto_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendido',
            fields=[
                ('id_compra', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id_Compra')),
                ('id_cliente', models.IntegerField(verbose_name='Id_Cliente')),
                ('nombre_P', models.CharField(max_length=30)),
                ('unidades', models.IntegerField(verbose_name='Unidades')),
                ('importe', models.FloatField(verbose_name='Importe')),
                ('nombre_M', models.CharField(max_length=30)),
            ],
        ),
    ]
