# Generated by Django 2.2.3 on 2022-11-10 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_auto_20221110_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marca',
            name='nombre_M',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='producto',
            name='detalles',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='producto',
            name='modelo',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre_P',
            field=models.CharField(max_length=30),
        ),
    ]
